#!/bin/sh

catfile=""
uuidcmd="uuid"

if hash $uuidcmd 2>/dev/null; then
    catfile="cat-$(uuid)".jpg
    echo "Saving cat image: $catfile"
else
    echo "---------------------------------------------"
    echo "This utility requires the command: $uuidcmd"
    echo "To insall it you can run the command..."
    echo "> brew install ossp-uuid"
    echo "which will install the $uuidcmd utility via brew"
    echo "---------------------------------------------"
    exit
fi

curl --output $catfile https://thiscatdoesnotexist.com
